server:
  port: 9002

spring:
  profiles:
    active: console
  application:
    name: careerwry-posting
  datasource:
    url: jdbc:mysql://localhost:3306/careerwry-posting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: careerwry
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#  flyway:
#    baseline-on-migrate: true # 기본 false 로 두고 필요하다면 true 를 주입하여 사용
#    baseline-version: 0.0.0

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework: INFO
