server:
  port: 9002

spring:
  application:
    name: careerwry-posting
  datasource:
    url: jdbc:mysql://localhost:3306/careerwry-posting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: careerwry
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework: INFO
